name: "sonobuoy iptables calico tests"
on:
  workflow_dispatch:
  schedule:
    # Daily, 3:00pm
    - cron: '00 15 * * *'

jobs:
  sonobuoy-iptables-calico-tests:
    runs-on: self-hosted
    env:
      GOPATH: /home/runner/work/k8devel/go
      GO111MODULE: auto
    steps:
      - uses: actions/checkout@v2
        with:
           path: main
           fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

        # Setup Go
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16.x'
      - uses: actions/checkout@master
        with:
          repository: thekubeworld/k8s-local-dev
          path: k8s-local-dev
      - run: |
          pushd ./k8s-local-dev
            ./k8s-local-dev calico
          popd
          #sudo apt update
          #sudo apt install wget -y
          wget https://github.com/vmware-tanzu/sonobuoy/releases/download/v0.50.0/sonobuoy_0.50.0_linux_amd64.tar.gz
          sudo tar zxvf sonobuoy_0.50.0_linux_amd64.tar.gz -C /bin
          sonobuoy run --skip-preflight --e2e-focus  "\[sig-network\]|\[Conformance\]" --e2e-skip "\[Feature:IPv6DualStackAlphaFeature\]|\[Feature:SCTP\]" --timeout 86400 --wait
      - name: Commit files
        run: |
          pushd ./main
            git config --local user.email "action@github.com"
            git config --local user.name "github-actions"
            curdate=$(date +"%m-%d-%Y-%k:%M:%S")
            git fetch && git rebase
            mkdir -p kind-iptables-conf/calico/"$curdate"/sonobuoy/
            outfile=$(sonobuoy retrieve)
            sonobuoy results "$outfile" &> kind-iptables-conf/calico/"$curdate"/sonobuoy/results.log
            sonobuoy e2e "$outfile" &> kind-iptables-conf/calico/"$curdate"/sonobuoy/e2e.log
            mv "$outfile" kind-iptables-conf/calico/"$curdate"/sonobuoy/
            git add kind-iptables-conf/
            git commit -m "Add output from sonobuoy tests" -a
          popd
        shell: bash
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          directory: main
